# Generated by Django 5.2.3 on 2026-03-10 20:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0015_project_file_sharing'),
        ('quotes', '0007_workflow_quote_payment_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount to be charged in the smallest currency unit.', max_digits=10)),
                ('currency', models.CharField(default='usd', help_text='Three-letter ISO currency code (e.g. usd, eur, zar).', max_length=10)),
                ('stripe_payment_intent', models.CharField(blank=True, help_text='Stripe PaymentIntent ID for this payment.', max_length=255)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', help_text='Current status of the payment.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Timestamp when the payment was confirmed as paid.', null=True)),
                ('client', models.ForeignKey(blank=True, help_text='Business client this Stripe payment belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stripe_payments', to='clients.client')),
                ('quote', models.ForeignKey(help_text='Quote this payment is associated with.', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='quotes.quote')),
                ('user', models.ForeignKey(blank=True, help_text='User who initiated the payment (if applicable).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
