# Generated by Django 5.2.3 on 2026-03-11 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_project_file_sharing'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_payment_intent',
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_reference',
            field=models.CharField(blank=True, help_text='Payment provider reference/transaction ID for this payment.', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Business client this external payment belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_payments', to='clients.client'),
        ),
    ]
