# Generated by Django 5.2.3 on 2026-03-22 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Action type: login, logout, profile_update, quote_approved, quote_declined, etc.', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_type', models.CharField(blank=True, help_text='Related model: quote, project, invoice', max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='Related object ID', null=True)),
                ('details', models.TextField(blank=True, help_text='Extra context (e.g. quote title, project name)')),
                ('user', models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
