# Generated by Django 5.2.3 on 2026-02-05 21:15

import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_change_quote_to_onetoone'),
        ('quotes', '0002_quote_admin_response_quote_replied_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount still due (calculated automatically)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid by client', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_address',
            field=models.TextField(blank=True, help_text='Client address (if available)', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_company',
            field=models.CharField(blank=True, help_text='Client company name (copied from quote at creation)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_email',
            field=models.EmailField(help_text='Client email (copied from quote at creation)', max_length=254),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_name',
            field=models.CharField(help_text='Client name (copied from quote at creation)', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_phone',
            field=models.CharField(blank=True, help_text='Client phone (copied from quote at creation)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_vat_number',
            field=models.CharField(blank=True, help_text='Client VAT number (if applicable)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(help_text='Date payment is due (defaults to 30 days from issue date)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Unique invoice number (auto-generated on save if empty)', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date invoice was issued (defaults to today)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_date',
            field=models.DateField(blank=True, help_text='Date payment was received', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal before VAT (defaults from quote estimated_amount)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount including VAT (defaults from quote estimated_amount)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT amount (calculated automatically)', max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('quote',), name='unique_quote_invoice'),
        ),
    ]
