# Generated by Django 5.2.3 on 2026-02-06 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_add_quote_client_fk'),
        ('invoices', '0003_allow_blank_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client (business entity) this invoice belongs to; set from quote when creating from quote', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.client'),
        ),
    ]
