"""
Django settings for PathyCodeback project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
from datetime import timedelta
import os

# Build paths: PathyCodeback/settings.py -> parent.parent = project root (manage.py location)
BASE_DIR = Path(__file__).resolve().parent.parent

if os.environ.get('DJANGO_DEBUG_PATHS', '').lower() == 'true':
    import logging
    logging.getLogger(__name__).info(
        "[DEBUG] BASE_DIR: %s, MEDIA_ROOT: %s", BASE_DIR, BASE_DIR / 'media'
    )


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-fallback-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,0.0.0.0', cast=Csv())



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # CORS support for React frontend
    'django_filters',  # Django filtering for REST framework
    'users',  # Custom app for user management
    'rest_framework',  # Django REST Framework for API development
    'projects',  # Custom app for project management
    'services',  # Custom app for service management
    'blog',  # Custom app for blog management
    'contact', # Custom app for contact management
    'newsletter',  # Newsletter subscription app
    'testimonials',  # Testimonials app
    'about',  # About Us app
    'quotes',  # Quotes/Estimates app
    'invoices',  # Invoices app
    'clients',  # Clients and case studies app
    'messaging',  # Internal messaging (threads per project)
    'payments',  # Payments and Stripe integration
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PathyCodeback.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'PathyCodeback' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PathyCodeback.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.sqlite3'),
        'NAME': config('DB_NAME', default=BASE_DIR / 'db.sqlite3'),
        'USER': config('DB_USER', default=''),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default=''),
        'PORT': config('DB_PORT', default=''),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Custom user model for user management
AUTH_USER_MODEL = 'users.CustomUser'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploaded files)
MEDIA_URL = '/media/'
# BASE_DIR points to project root (where manage.py is), so media goes at root level
MEDIA_ROOT = BASE_DIR / 'media'

# Ensure media directory and upload subdirs exist at startup (projects, blog, about, clients, testimonials)
for subdir in ('', 'projects', 'blog', 'about', 'clients/logos', 'testimonials'):
    os.makedirs(os.path.join(str(MEDIA_ROOT), subdir), exist_ok=True)

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440  # 2.5 MB - files larger than this will be saved to disk
DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440  # 2.5 MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Configuration
# In development, allow all origins for easier testing
# In production, use CORS_ALLOWED_ORIGINS with specific domains
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_CREDENTIALS = True
else:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        # Add your production frontend URL here
    ]
    CORS_ALLOW_CREDENTIALS = True

# CORS Headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'EXCEPTION_HANDLER': 'PathyCodeback.exceptions.custom_exception_handler',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# JWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
}

# Email Configuration
# In development, emails are printed to console
# In production, configure SMTP settings
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@pathycodes.com')

# Frontend URL for password reset links
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')

# Base URL for API/media when building absolute URLs (e.g. in serializers when request is missing)
# Used so the frontend receives absolute media URLs even from scripts/celery.
PROJECT_BASE_URL = config('PROJECT_BASE_URL', default='http://localhost:8000')

# PayFast configuration (sandbox defaults; replace with real values in production)
# NOTE: PAYFAST_NOTIFY_URL must be publicly reachable. PayFast sends ITN (Instant Transaction
# Notification) from their servers. For local dev, use ngrok: run `ngrok http 8000` and set
# PROJECT_BASE_URL to the ngrok URL (e.g. https://abc123.ngrok-free.app).
PAYFAST_MERCHANT_ID = config("PAYFAST_MERCHANT_ID", default="10000100")
PAYFAST_MERCHANT_KEY = config("PAYFAST_MERCHANT_KEY", default="46f0cd694581a")
PAYFAST_RETURN_URL = config(
    "PAYFAST_RETURN_URL", default=f"{PROJECT_BASE_URL}/payments/success/"
)
PAYFAST_CANCEL_URL = config(
    "PAYFAST_CANCEL_URL", default=f"{PROJECT_BASE_URL}/payments/cancel/"
)
PAYFAST_NOTIFY_URL = config(
    "PAYFAST_NOTIFY_URL", default=f"{PROJECT_BASE_URL}/payments/notify/"
)
PAYFAST_SANDBOX_URL = config(
    "PAYFAST_SANDBOX_URL", default="https://sandbox.payfast.co.za/eng/process"
)
# Passphrase for ITN signature verification (set in PayFast merchant settings). Empty = skip verification.
PAYFAST_PASSPHRASE = config("PAYFAST_PASSPHRASE", default="")

