# Generated by Django 5.2.3 on 2026-02-18 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_project_client_to_entity'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client (business entity) when submitted by authenticated user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to='clients.client'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Read', 'Read'), ('Replied', 'Replied'), ('Archived', 'Archived')], default='New', help_text='Message status for tracking', max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
