# Generated by Django 5.2.3 on 2025-10-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Short title or name of the service (e.g., 'Web Development')", max_length=100)),
                ('description', models.TextField(help_text='Detailed explanation of the service')),
                ('icon', models.CharField(blank=True, help_text="Optional: FontAwesome class or custom icon name for frontend display (e.g., 'fas fa-code')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp automatically set when the service is created')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-created_at'],
            },
        ),
    ]
