# Generated by Django 5.2.3 on 2025-11-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_migrate_title_to_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='categories',
            field=models.CharField(blank=True, help_text='Comma-separated list of categories', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='features',
            field=models.TextField(blank=True, help_text='JSON array or comma-separated list of features'),
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default='Service', help_text="Name of the service (e.g., 'Web Development')", max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price of the service (optional)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp automatically updated when the service is modified'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, help_text='Legacy title field (deprecated, use name instead)', max_length=100, null=True),
        ),
    ]
