# Generated by Django 5.2.3 on 2026-01-22 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Client company name', max_length=255)),
                ('logo', models.ImageField(blank=True, help_text='Client logo image', null=True, upload_to='clients/logos/')),
                ('industry', models.CharField(blank=True, help_text='Industry sector (e.g., Technology, Healthcare, Finance)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Brief description of the client')),
                ('is_public', models.BooleanField(default=False, help_text='Display on public website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('problem', models.TextField(help_text='The problem or challenge that was addressed')),
                ('solution', models.TextField(help_text='The solution that was implemented')),
                ('result', models.TextField(help_text='The results and outcomes achieved')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text="Key metrics as JSON (e.g., {'revenue': '+50%', 'users': '10K'})")),
                ('testimonial', models.TextField(blank=True, help_text='Optional client testimonial')),
                ('is_public', models.BooleanField(default=False, help_text='Display on public website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='The client this case study belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='case_studies', to='clients.client')),
            ],
            options={
                'verbose_name': 'Case Study',
                'verbose_name_plural': 'Case Studies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(blank=True, help_text='Comma-separated list of technologies used', max_length=500)),
                ('repo_url', models.URLField(blank=True, help_text='GitHub repository URL (optional)', null=True)),
                ('live_url', models.URLField(blank=True, help_text='Live demo URL (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='The client this project belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.client')),
            ],
            options={
                'verbose_name': 'Client Project',
                'verbose_name_plural': 'Client Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
