# Generated by Django 5.2.3 on 2026-02-06 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_backfill_client_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_entity',
            field=models.ForeignKey(blank=True, help_text='Client (business entity) that owns this project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, help_text='[Migration] Will be replaced by client_entity', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
