# Generated by Django 5.2.3 on 2026-03-06 08:48

import django.core.validators
from django.db import migrations, models


def remap_project_statuses(apps, schema_editor):
    Project = apps.get_model('clients', 'Project')
    for p in Project.objects.all().only('id', 'status', 'progress_percentage'):
        old = (p.status or '').lower()
        if old in ('pending', ''):
            p.status = 'planning'
            if p.progress_percentage == 0:
                p.progress_percentage = 5
        elif old == 'in_progress':
            p.status = 'development'
            if p.progress_percentage == 0:
                p.progress_percentage = 50
        elif old == 'completed':
            p.status = 'completed'
            p.progress_percentage = 100
        p.save(update_fields=['status', 'progress_percentage'])


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_client_project_internal_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress_percentage',
            field=models.PositiveSmallIntegerField(default=0, help_text='Project progress percentage (0-100). Clients can view; admin updates.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('design', 'Design'), ('development', 'Development'), ('testing', 'Testing'), ('completed', 'Completed')], default='planning', help_text='Current stage of the project', max_length=20),
        ),
        migrations.RunPython(remap_project_statuses, migrations.RunPython.noop),
    ]
