# Generated by Django 5.2.3 on 2026-03-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_project_progress_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, help_text='Project start date (set when project is auto-created from paid invoice)', null=True),
        ),
    ]
