# Generated by Django 5.2.3 on 2026-03-07 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_workflow_quote_payment_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Uploaded file (stored in MEDIA_ROOT)', upload_to='project_files/%Y/%m/')),
                ('description', models.CharField(blank=True, help_text='Optional description of the file', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(help_text='Project this file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='project_files', to='clients.project')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded the file (client or admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_project_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project File',
                'verbose_name_plural': 'Project Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
