# Generated by Django 5.2.3 on 2026-03-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_project_file_sharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional cover image for this project (shown on public projects page)', null=True, upload_to='clients/projects/'),
        ),
    ]
