# Generated by Django 5.2.3 on 2026-03-11 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
