# Generated by Django 5.2.3 on 2026-03-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Main hero image for this project (used on public projects page)', null=True, upload_to='clients/projects/hero/'),
        ),
    ]
