# Generated by Django 5.2.3 on 2025-10-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the blog post.', max_length=255)),
                ('body', models.TextField(help_text='The main content of the blog post.')),
                ('category', models.CharField(help_text='The category the blog post belongs to, e.g., Tech, Lifestyle.', max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags to help categorize or search blog posts.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the post was created.')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
