# Generated by Django 5.2.3 on 2026-08-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_messagethread_wallpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagethread',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Custom sidebar cover photo', null=True, upload_to='messaging/covers/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='background_preset',
            field=models.CharField(default='workspace', help_text='Sidebar cover preset when background_image is empty', max_length=32),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='wallpaper_image',
            field=models.ImageField(blank=True, help_text='Custom chat box wallpaper', null=True, upload_to='messaging/wallpapers/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='wallpaper_preset',
            field=models.CharField(default='workspace', help_text='Chat wallpaper preset when wallpaper_image is empty', max_length=32),
        ),
    ]
