# Generated by Django 5.2.3 on 2025-12-03 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=255)),
                ('hero_title', models.CharField(default='About PathyCode', max_length=255)),
                ('hero_subtitle', models.TextField(default='We are passionate about creating innovative solutions and delivering exceptional results.', help_text='Subtitle text for the hero section')),
                ('our_story_title', models.CharField(default='Our Story', max_length=255)),
                ('our_story_content', models.TextField(default='PathyCode was founded with a vision to empower businesses and individuals through cutting-edge technology solutions.', help_text='Main story content')),
                ('mission_title', models.CharField(default='Our Mission', max_length=255)),
                ('mission_content', models.TextField(default='To deliver innovative, high-quality solutions that drive success for our clients.', help_text='Mission statement')),
                ('vision_title', models.CharField(default='Our Vision', max_length=255)),
                ('vision_content', models.TextField(default='To be a leading force in technology innovation, recognized for excellence and impact.', help_text='Vision statement')),
                ('why_choose_us_title', models.CharField(default='Why Choose Us', max_length=255)),
                ('why_choose_us_content', models.TextField(default='We combine expertise, innovation, and dedication to deliver exceptional results.', help_text='Why choose us content')),
                ('image', models.ImageField(blank=True, help_text='Main about us image', null=True, upload_to='about/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text="FontAwesome icon class (e.g., 'fas fa-heart')", max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='about.aboutus')),
            ],
            options={
                'verbose_name': 'Value',
                'verbose_name_plural': 'Values',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
