# Generated by Django 5.2.3 on 2026-02-18 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_project_client_to_entity'),
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client (business entity) when submitted by authenticated user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='clients.client'),
        ),
    ]
