# Generated by Django 5.2.3 on 2026-06-29 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('quote_reviewed', 'Quote reviewed'), ('payment_completed', 'Payment completed'), ('invoice_generated', 'Invoice generated'), ('new_message', 'New message')], default='quote_reviewed', max_length=40)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_app_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'In-app notification',
                'verbose_name_plural': 'In-app notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
