# Generated by Django 5.2.3 on 2026-08-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inappnotification',
            name='event_type',
            field=models.CharField(choices=[('quote_submitted', 'Quote submitted'), ('quote_reviewed', 'Quote reviewed'), ('quote_approved', 'Quote approved'), ('quote_rejected', 'Quote rejected'), ('quote_changes_requested', 'Quote changes requested'), ('quote_paid', 'Quote paid'), ('payment_completed', 'Payment completed'), ('payment_failed', 'Payment failed'), ('invoice_generated', 'Invoice generated'), ('invoice_paid', 'Invoice paid'), ('invoice_overdue', 'Invoice overdue'), ('invoice_payment_reminder', 'Invoice payment reminder'), ('quote_payment_reminder', 'Quote payment reminder'), ('project_created', 'Project created'), ('project_updated', 'Project updated'), ('project_completed', 'Project completed'), ('task_assigned', 'Task assigned'), ('task_completed', 'Task completed'), ('task_updated', 'Task updated'), ('file_uploaded', 'File uploaded'), ('calendar_event', 'Calendar event'), ('new_message', 'New message'), ('thread_created', 'Message thread created'), ('testimonial_submitted', 'Testimonial submitted'), ('testimonial_approved', 'Testimonial approved'), ('profile_updated', 'Profile updated'), ('password_changed', 'Password changed'), ('email_changed', 'Email changed'), ('contact_submitted', 'Contact form submitted'), ('newsletter_subscribed', 'Newsletter subscribed'), ('user_registered', 'User registered')], default='quote_reviewed', max_length=40),
        ),
    ]
