# Generated by Django 5.2.3 on 2026-01-25 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='admin_response',
            field=models.TextField(blank=True, help_text="Admin's response to the client (sent via email when status changes to 'Replied')", null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='replied_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when admin sent response to client', null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='requirements_accepted',
            field=models.BooleanField(default=False, help_text='Whether the client has read and accepted the requirements'),
        ),
        migrations.AddField(
            model_name='quote',
            name='requirements_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when requirements were accepted', null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Web Development', 'Web Development'), ('Backend/API Development', 'Backend/API Development'), ('Mobile App Development', 'Mobile App Development'), ('E-commerce Development', 'E-commerce Development'), ('Maintenance/Support', 'Maintenance/Support'), ('Design', 'Design'), ('Consulting', 'Consulting'), ('Other', 'Other')], help_text='Type of service requested', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='timeline',
            field=models.CharField(blank=True, choices=[('1-2 weeks', '1-2 weeks'), ('2-4 weeks', '2-4 weeks'), ('1-2 months', '1-2 months'), ('2-3 months', '2-3 months'), ('3-6 months', '3-6 months'), ('6+ months', '6+ months'), ('Flexible', 'Flexible')], help_text='Expected project timeline', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the quote was approved', null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Admin user assigned to handle this quote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quote',
            name='budget_range',
            field=models.CharField(blank=True, help_text="Client's budget range", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='client_email',
            field=models.EmailField(help_text='Email address for communication and notifications', max_length=254),
        ),
        migrations.AlterField(
            model_name='quote',
            name='client_name',
            field=models.CharField(help_text='Full name of the client requesting the quote', max_length=255),
        ),
        migrations.AlterField(
            model_name='quote',
            name='client_phone',
            field=models.CharField(blank=True, help_text='Optional phone number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='company_name',
            field=models.CharField(blank=True, help_text='Optional company name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the quote request was submitted'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='deadline',
            field=models.DateField(blank=True, help_text='Desired project completion date', null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='estimated_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Admin-provided estimated amount for the project', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes for admin use (not visible to client)', null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='project_description',
            field=models.TextField(help_text='Detailed description of project requirements and features'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='project_title',
            field=models.CharField(help_text='Title or name of the project', max_length=255),
        ),
        migrations.AlterField(
            model_name='quote',
            name='project_type',
            field=models.CharField(blank=True, help_text='Legacy field - use service_type instead', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Replied', 'Replied'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', help_text='Current status of the quote request', max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
    ]
