# Generated by Django 5.2.3 on 2026-02-06 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_add_quote_client_fk'),
        ('quotes', '0002_quote_admin_response_quote_replied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client (business entity) this quote belongs to; set when submitted by authenticated user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='clients.client'),
        ),
    ]
