# Generated by Django 5.2.3 on 2026-02-20 19:47

from django.db import migrations, models


def migrate_status_to_lowercase(apps, schema_editor):
    """Map old status values to new: pending, replied, approved, declined."""
    Quote = apps.get_model('quotes', 'Quote')
    mapping = {
        'Pending': 'pending',
        'Reviewed': 'replied',
        'Replied': 'replied',
        'Approved': 'approved',
        'Rejected': 'declined',
        'In Progress': 'pending',
        'Completed': 'approved',
    }
    for quote in Quote.objects.all():
        new_status = mapping.get(quote.status, 'pending')
        if quote.status != new_status:
            quote.status = new_status
            quote.save(update_fields=['status'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_backfill_quote_client'),
    ]

    operations = [
        migrations.RunPython(migrate_status_to_lowercase, noop),
        migrations.RenameField(
            model_name='quote',
            old_name='replied_at',
            new_name='responded_at',
        ),
        migrations.AddField(
            model_name='quote',
            name='client_decision_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when client approved or declined the quote', null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='admin_response',
            field=models.TextField(blank=True, help_text="Admin's response to the client (sent via email when status changes to 'replied')", null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the quote was approved (legacy; use client_decision_at for client decision)', null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('replied', 'Replied'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', help_text='Current status of the quote request', max_length=20),
        ),
    ]
