# Generated by Django 5.2.3 on 2026-02-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_quote_workflow_status_responded_client_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='payment_url',
            field=models.URLField(blank=True, help_text='Payment link for the client; set when admin marks quote as replied', max_length=500, null=True),
        ),
    ]
