# Generated by Django 5.2.3 on 2026-03-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_add_quote_payment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='estimated_delivery_time',
            field=models.CharField(blank=True, help_text="Admin-estimated delivery time (e.g. '2-4 weeks'); shown to client when status = reviewed", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='admin_response',
            field=models.TextField(blank=True, help_text='Admin notes/response to the client (visible in Client Portal when status = reviewed)', null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='estimated_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Proposed price from admin (shown to client when status = reviewed)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('declined', 'Declined'), ('replied', 'Replied (legacy)'), ('invoiced', 'Invoiced (legacy)'), ('paid', 'Paid (legacy)')], default='pending', help_text='Current status of the quote request', max_length=20),
        ),
    ]
