# Generated by Django 5.2.3 on 2026-03-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_workflow_quote_payment_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='client_response',
            field=models.TextField(blank=True, help_text='Client feedback when requesting changes', null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='deliverables',
            field=models.TextField(blank=True, help_text='Deliverables (can store as bullet text)', null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='proposal_timeline',
            field=models.CharField(blank=True, help_text='Proposed project timeline', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='scope',
            field=models.TextField(blank=True, help_text='Project scope for the proposal', null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='terms',
            field=models.TextField(blank=True, help_text='Terms and conditions for the proposal', null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('declined', 'Declined (legacy)'), ('replied', 'Replied (legacy)'), ('invoiced', 'Invoiced (legacy)')], default='pending', help_text='Current status of the quote request', max_length=20),
        ),
    ]
